import { Show } from "@/types";

export const SHOWS: Omit<Show, "_id">[] = [
  {
    title: "Prison Break",
    slug: "prison-break",
    description: "A structural engineer devises an elaborate plan to help his brother escape death row — and pulls off one of the most daring prison breaks in history.",
    bannerImage: "/prison-break.jpg",
    posterImage: "/prison-break.jpg",
    genre: ["Thriller", "Drama", "Action"],
    releaseYear: 2005,
    totalSeasons: 5,
    difficulty: "Medium",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Game of Thrones",
    slug: "game-of-thrones",
    description: "Noble families fight for control of the mythical land of Westeros while an ancient enemy returns after being dormant for thousands of years.",
    bannerImage: "/got.webp",
    posterImage: "/got.webp",
    genre: ["Fantasy", "Drama", "Action"],
    releaseYear: 2011,
    totalSeasons: 8,
    difficulty: "Hard",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Breaking Bad",
    slug: "breaking-bad",
    description: "A chemistry teacher diagnosed with terminal cancer teams up with a former student to build a drug empire — and transforms into someone unrecognisable.",
    bannerImage: "/breaking-bad.webp",
    posterImage: "/breaking-bad.webp",
    genre: ["Crime", "Drama", "Thriller"],
    releaseYear: 2008,
    totalSeasons: 5,
    difficulty: "Hard",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Avatar: The Last Airbender",
    slug: "avatar-the-last-airbender",
    description: "A young boy discovers he is the Avatar — the only person who can master all four elements — and must use his powers to stop a ruthless war.",
    bannerImage: "/avatar.avif",
    posterImage: "/avatar.avif",
    genre: ["Animation", "Adventure", "Fantasy"],
    releaseYear: 2005,
    totalSeasons: 3,
    difficulty: "Easy",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Better Call Saul",
    slug: "better-call-saul",
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the time leading up to his fateful meeting with Walter White.",
    bannerImage: "/bcs.jpg",
    posterImage: "/bcs.jpg",
    genre: ["Crime", "Drama", "Thriller"],
    releaseYear: 2015,
    totalSeasons: 6,
    difficulty: "Hard",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Attack on Titan",
    slug: "attack-on-titan",
    description: "Humanity lives inside cities surrounded by enormous walls protecting them from Titans — gigantic humanoid creatures who devour humans seemingly without reason.",
    bannerImage: "/aot.jpg",
    posterImage: "/aot.jpg",
    genre: ["Animation", "Action", "Dark Fantasy"],
    releaseYear: 2013,
    totalSeasons: 4,
    difficulty: "Medium",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Naruto Shippuden",
    slug: "naruto-shippuden",
    description: "Naruto Uzumaki returns after years of training to find his village threatened by a powerful organisation — and chases his dream of becoming Hokage.",
    bannerImage: "/naruto.jpg",
    posterImage: "/naruto.jpg",
    genre: ["Animation", "Action", "Adventure"],
    releaseYear: 2007,
    totalSeasons: 21,
    difficulty: "Medium",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Suits",
    slug: "suits",
    description: "A college dropout with a photographic memory starts working as an associate for a top Manhattan law firm — hiding the fact that he never went to law school.",
    bannerImage: "/suits.jpg",
    posterImage: "/suits.jpg",
    genre: ["Drama", "Legal", "Comedy"],
    releaseYear: 2011,
    totalSeasons: 9,
    difficulty: "Easy",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Money Heist",
    slug: "money-heist",
    description: "A criminal mastermind who goes by The Professor recruits eight thieves with specific skills to carry out an ambitious plan — rob the Royal Mint of Spain.",
    bannerImage: "/money-heist.jpg",
    posterImage: "/money-heist.jpg",
    genre: ["Crime", "Thriller", "Drama"],
    releaseYear: 2017,
    totalSeasons: 5,
    difficulty: "Medium",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Vampire Diaries",
    slug: "vampire-diaries",
    description: "A teenage girl falls in love with a centuries-old vampire while his dangerous brother threatens their small town — and dark secrets begin to surface.",
    bannerImage: "/vampire-diaries.webp",
    posterImage: "/vampire-diaries.webp",
    genre: ["Drama", "Fantasy", "Romance"],
    releaseYear: 2009,
    totalSeasons: 8,
    difficulty: "Easy",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "Stranger Things",
    slug: "stranger-things",
    description: "When a boy vanishes in a small town, his friends and family uncover a government conspiracy and supernatural forces — and a strange little girl with psychokinetic powers.",
    bannerImage: "/stranger-things.jpg",
    posterImage: "/stranger-things.jpg",
    genre: ["Sci-Fi", "Horror", "Drama"],
    releaseYear: 2016,
    totalSeasons: 4,
    difficulty: "Medium",
    totalQuestions: 200,
    isActive: true,
  },
  {
    title: "FROM",
    slug: "from",
    description: "Residents of a mysterious town in middle America are unable to leave — trapped in a nightmare while battling terrifying creatures that emerge at night.",
    bannerImage: "/from.png",
    posterImage: "/from.png",
    genre: ["Horror", "Mystery", "Sci-Fi"],
    releaseYear: 2022,
    totalSeasons: 3,
    difficulty: "Hard",
    totalQuestions: 200,
    isActive: true,
  },
];